#!/usr/bin/env python3
"""make_button_icons.py -- the Switch's buttons as white pictures, for the
console-style button prompts at the bottom of the menus (ssr_prompt.c).

The console editions of the game showed "(+) SELECT  (B) BACK  (A) OK" in
white at the bottom right of every menu. This draws the Switch's buttons in
that style: the face buttons, + and - as white discs with the letter cut in
the game's dark blue, the shoulders as white rounded bars, the sticks as white
rings, the D-pad as a white cross -- all with a thin dark rim so they read on
light backgrounds too (the approach of the Plants vs. Zombies port's
tools/make_button_icons.py, drawn for this game).

  resources/buttons/icons.png       every button at 96 pixels high, in a row
  source/ssr_button_icons.h         where each is in that row (generated)
The letters: DejaVu Sans Bold (tools/fonts, free licence: LICENSE_DEJAVU).
Run it again after changing the drawing (needs Pillow).
"""
import os

from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, 'resources', 'buttons')
FONT = os.path.join(HERE, 'fonts', 'DejaVuSans-Bold.ttf')

H = 96   # master height
SS = 4   # drawn at 4x, then reduced: smooth edges
WHITE = (255, 255, 255, 255)
INK = (20, 38, 84, 255)      # the game's dark blue, for the letters
RIM = (10, 20, 46, 150)      # a thin dark rim

BUTTONS = [  # (name, kind, label)
    ('A', 'round', 'A'), ('B', 'round', 'B'), ('X', 'round', 'X'), ('Y', 'round', 'Y'),
    ('PLUS', 'round', '+'), ('MINUS', 'round', '-'), ('L', 'shoulder', 'L'), ('R', 'shoulder', 'R'),
    ('ZL', 'trigger', 'ZL'), ('ZR', 'trigger', 'ZR'), ('LSTICK', 'stick', 'L'), ('RSTICK', 'stick', 'R'),
    ('DPAD', 'dpad', ''),
]


def font(px):
    return ImageFont.truetype(FONT, px)


def centred(d, box, text, px, fill):
    f = font(px)
    l, t, r, b = d.textbbox((0, 0), text, font=f)
    x0, y0, x1, y1 = box
    d.text(((x0 + x1 - (r - l)) / 2 - l, (y0 + y1 - (b - t)) / 2 - t), text, font=f, fill=fill)


def draw(kind, label):
    h = H * SS
    w = {'round': h, 'stick': h, 'dpad': h, 'shoulder': int(h * 1.25), 'trigger': int(h * 1.45)}[kind]
    im = Image.new('RGBA', (w, h), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    m = int(h * 0.06)   # margin
    rim = int(h * 0.035)
    if kind == 'round':
        d.ellipse((m - rim, m - rim, w - m + rim, h - m + rim), fill=RIM)
        d.ellipse((m, m, w - m, h - m), fill=WHITE)
        if label == '+':
            t = int(h * 0.09)
            c = h // 2
            d.rectangle((c - int(h * 0.24), c - t, c + int(h * 0.24), c + t), fill=INK)
            d.rectangle((c - t, c - int(h * 0.24), c + t, c + int(h * 0.24)), fill=INK)
        elif label == '-':
            t = int(h * 0.09)
            c = h // 2
            d.rectangle((c - int(h * 0.24), c - t, c + int(h * 0.24), c + t), fill=INK)
        else:
            centred(d, (m, m, w - m, h - m), label, int(h * 0.56), INK)
    elif kind in ('shoulder', 'trigger'):
        r = int(h * 0.30)
        box = (m, int(h * 0.16), w - m, h - int(h * 0.16))
        d.rounded_rectangle((box[0] - rim, box[1] - rim, box[2] + rim, box[3] + rim), r + rim, fill=RIM)
        d.rounded_rectangle(box, r, fill=WHITE)
        centred(d, box, label, int(h * 0.46), INK)
    elif kind == 'stick':
        d.ellipse((m - rim, m - rim, w - m + rim, h - m + rim), fill=RIM)
        d.ellipse((m, m, w - m, h - m), fill=WHITE)
        i = int(h * 0.17)
        d.ellipse((m + i, m + i, w - m - i, h - m - i), fill=INK)
        centred(d, (m + i, m + i, w - m - i, h - m - i), label, int(h * 0.38), WHITE)
    elif kind == 'dpad':
        t = int(h * 0.17)   # half the arm's width
        c = h // 2
        a = h // 2 - m      # arm length
        for rr, col in ((rim, RIM), (0, WHITE)):
            d.rounded_rectangle((c - a - rr, c - t - rr, c + a + rr, c + t + rr), int(h * 0.05) + rr, fill=col)
            d.rounded_rectangle((c - t - rr, c - a - rr, c + t + rr, c + a + rr), int(h * 0.05) + rr, fill=col)
        d.ellipse((c - int(t * 0.55), c - int(t * 0.55), c + int(t * 0.55), c + int(t * 0.55)), fill=(200, 208, 224, 255))
    return im.resize((w // SS, H), Image.LANCZOS)


def main():
    os.makedirs(OUT, exist_ok=True)
    pics = [draw(k, l) for _, k, l in BUTTONS]
    total = sum(p.width for p in pics)
    row = Image.new('RGBA', (total, H), (0, 0, 0, 0))
    x = 0
    cells = []
    for p in pics:
        row.paste(p, (x, 0))
        cells.append((x, p.width))
        x += p.width
    row.save(os.path.join(OUT, 'icons.png'), optimize=True)
    with open(os.path.join(ROOT, 'source', 'ssr_button_icons.h'), 'w') as f:
        f.write('/* ssr_button_icons.h -- generated by tools/make_button_icons.py: where each\n'
                ' * button is in resources/buttons/icons.png (one row, %d pixels high). */\n' % H)
        f.write('#define SSR_ICON_H %d\n#define SSR_ICON_ROW_W %d\n#define SSR_ICON_COUNT %d\n' % (H, total, len(BUTTONS)))
        f.write('enum {\n' + ''.join('  SSR_ICON_%s,\n' % n for n, _, _ in BUTTONS) + '};\n')
        f.write('static const struct {\n  int x, w;\n} k_ssr_icons[SSR_ICON_COUNT] = {\n')
        for (n, _, _), (cx, cw) in zip(BUTTONS, cells):
            f.write('    {%d, %d}, /* %s */\n' % (cx, cw, n))
        f.write('};\n')
    print('icons.png: %d x %d, %d buttons' % (total, H, len(BUTTONS)))


if __name__ == '__main__':
    main()
