/* imports.c -- GENERATED by runtime/tools/gen_imports.py; do not edit.
 *
 * Every import of libssasr that no loaded module
 * exports (gl* aside: the GL layer serves those), mapped to the host
 * function or object that serves it: b_* shims for the bionic ABI
 * (bionic_*.c, android_ndk.c, gl_*.c, the port's files), and newlib
 * directly where the two ABIs agree. Declared through asm labels so no
 * C prototype is needed (or can conflict): only the address is taken
 * here. The search over the table is the runtime's imports_lookup.c.
 *
 * Weak imports bound to NULL on purpose: __cxa_begin_cleanup, __cxa_call_unexpected, __cxa_type_match.
 * MIT.
 */
#include "imports.h"

extern const char sym___errno[] __asm__("__errno");
extern const char sym_acosf[] __asm__("acosf");
extern const char sym_asinf[] __asm__("asinf");
extern const char sym_atan2f[] __asm__("atan2f");
extern const char sym_atanf[] __asm__("atanf");
extern const char sym_atoi[] __asm__("atoi");
extern const char sym_b___aeabi_atexit[] __asm__("b___aeabi_atexit");
extern const char sym_b___android_log_print[] __asm__("b___android_log_print");
extern const char sym_b___android_log_write[] __asm__("b___android_log_write");
extern const char sym_b___cxa_finalize[] __asm__("b___cxa_finalize");
extern const char sym_b___cxa_pure_virtual[] __asm__("b___cxa_pure_virtual");
extern const char sym_b___gnu_Unwind_Find_exidx[] __asm__("b___gnu_Unwind_Find_exidx");
extern const char sym_b___isfinitef[] __asm__("b___isfinitef");
extern const char sym_b___sF[] __asm__("b___sF");
extern const char sym_b___stack_chk_fail[] __asm__("b___stack_chk_fail");
extern const char sym_b___stack_chk_guard[] __asm__("b___stack_chk_guard");
extern const char sym_b__ctype_[] __asm__("b__ctype_");
extern const char sym_b__tolower_tab_[] __asm__("b__tolower_tab_");
extern const char sym_b__toupper_tab_[] __asm__("b__toupper_tab_");
extern const char sym_b_abort[] __asm__("b_abort");
extern const char sym_b_bind[] __asm__("b_bind");
extern const char sym_b_clock_gettime[] __asm__("b_clock_gettime");
extern const char sym_b_close[] __asm__("b_close");
extern const char sym_b_dlclose[] __asm__("b_dlclose");
extern const char sym_b_dlerror[] __asm__("b_dlerror");
extern const char sym_b_dlopen[] __asm__("b_dlopen");
extern const char sym_b_dlsym[] __asm__("b_dlsym");
extern const char sym_b_exit[] __asm__("b_exit");
extern const char sym_b_fclose[] __asm__("b_fclose");
extern const char sym_b_fcntl[] __asm__("b_fcntl");
extern const char sym_b_fdopen[] __asm__("b_fdopen");
extern const char sym_b_feof[] __asm__("b_feof");
extern const char sym_b_fflush[] __asm__("b_fflush");
extern const char sym_b_fgetc[] __asm__("b_fgetc");
extern const char sym_b_fgets[] __asm__("b_fgets");
extern const char sym_b_floor[] __asm__("b_floor");
extern const char sym_b_floorf[] __asm__("b_floorf");
extern const char sym_b_fopen[] __asm__("b_fopen");
extern const char sym_b_fprintf[] __asm__("b_fprintf");
extern const char sym_b_fputc[] __asm__("b_fputc");
extern const char sym_b_fputs[] __asm__("b_fputs");
extern const char sym_b_fread[] __asm__("b_fread");
extern const char sym_b_fseek[] __asm__("b_fseek");
extern const char sym_b_ftell[] __asm__("b_ftell");
extern const char sym_b_fwrite[] __asm__("b_fwrite");
extern const char sym_b_getenv[] __asm__("b_getenv");
extern const char sym_b_gettimeofday[] __asm__("b_gettimeofday");
extern const char sym_b_lseek[] __asm__("b_lseek");
extern const char sym_b_memcpy[] __asm__("b_memcpy");
extern const char sym_b_memmove[] __asm__("b_memmove");
extern const char sym_b_memset[] __asm__("b_memset");
extern const char sym_b_nanosleep[] __asm__("b_nanosleep");
extern const char sym_b_open[] __asm__("b_open");
extern const char sym_b_printf[] __asm__("b_printf");
extern const char sym_b_pthread_cond_broadcast[] __asm__("b_pthread_cond_broadcast");
extern const char sym_b_pthread_cond_wait[] __asm__("b_pthread_cond_wait");
extern const char sym_b_pthread_create[] __asm__("b_pthread_create");
extern const char sym_b_pthread_getspecific[] __asm__("b_pthread_getspecific");
extern const char sym_b_pthread_join[] __asm__("b_pthread_join");
extern const char sym_b_pthread_key_create[] __asm__("b_pthread_key_create");
extern const char sym_b_pthread_key_delete[] __asm__("b_pthread_key_delete");
extern const char sym_b_pthread_mutex_destroy[] __asm__("b_pthread_mutex_destroy");
extern const char sym_b_pthread_mutex_init[] __asm__("b_pthread_mutex_init");
extern const char sym_b_pthread_mutex_lock[] __asm__("b_pthread_mutex_lock");
extern const char sym_b_pthread_mutex_unlock[] __asm__("b_pthread_mutex_unlock");
extern const char sym_b_pthread_mutexattr_destroy[] __asm__("b_pthread_mutexattr_destroy");
extern const char sym_b_pthread_mutexattr_init[] __asm__("b_pthread_mutexattr_init");
extern const char sym_b_pthread_mutexattr_settype[] __asm__("b_pthread_mutexattr_settype");
extern const char sym_b_pthread_once[] __asm__("b_pthread_once");
extern const char sym_b_pthread_self[] __asm__("b_pthread_self");
extern const char sym_b_pthread_setschedparam[] __asm__("b_pthread_setschedparam");
extern const char sym_b_pthread_setspecific[] __asm__("b_pthread_setspecific");
extern const char sym_b_putchar[] __asm__("b_putchar");
extern const char sym_b_puts[] __asm__("b_puts");
extern const char sym_b_raise[] __asm__("b_raise");
extern const char sym_b_read[] __asm__("b_read");
extern const char sym_b_recvfrom[] __asm__("b_recvfrom");
extern const char sym_b_remove[] __asm__("b_remove");
extern const char sym_b_sched_get_priority_min[] __asm__("b_sched_get_priority_min");
extern const char sym_b_sched_yield[] __asm__("b_sched_yield");
extern const char sym_b_sendto[] __asm__("b_sendto");
extern const char sym_b_setsockopt[] __asm__("b_setsockopt");
extern const char sym_b_snprintf[] __asm__("b_snprintf");
extern const char sym_b_socket[] __asm__("b_socket");
extern const char sym_b_sprintf[] __asm__("b_sprintf");
extern const char sym_b_sqrtf[] __asm__("b_sqrtf");
extern const char sym_b_usleep[] __asm__("b_usleep");
extern const char sym_b_vprintf[] __asm__("b_vprintf");
extern const char sym_b_vsnprintf[] __asm__("b_vsnprintf");
extern const char sym_b_vsprintf[] __asm__("b_vsprintf");
extern const char sym_calloc[] __asm__("calloc");
extern const char sym_cosf[] __asm__("cosf");
extern const char sym_exp[] __asm__("exp");
extern const char sym_expf[] __asm__("expf");
extern const char sym_fmax[] __asm__("fmax");
extern const char sym_fmodf[] __asm__("fmodf");
extern const char sym_free[] __asm__("free");
extern const char sym_log10f[] __asm__("log10f");
extern const char sym_logf[] __asm__("logf");
extern const char sym_lrand48[] __asm__("lrand48");
extern const char sym_malloc[] __asm__("malloc");
extern const char sym_memchr[] __asm__("memchr");
extern const char sym_memcmp[] __asm__("memcmp");
extern const char sym_pow[] __asm__("pow");
extern const char sym_powf[] __asm__("powf");
extern const char sym_qsort[] __asm__("qsort");
extern const char sym_realloc[] __asm__("realloc");
extern const char sym_sinf[] __asm__("sinf");
extern const char sym_srand48[] __asm__("srand48");
extern const char sym_sscanf[] __asm__("sscanf");
extern const char sym_strcasecmp[] __asm__("strcasecmp");
extern const char sym_strcat[] __asm__("strcat");
extern const char sym_strchr[] __asm__("strchr");
extern const char sym_strcmp[] __asm__("strcmp");
extern const char sym_strcpy[] __asm__("strcpy");
extern const char sym_strdup[] __asm__("strdup");
extern const char sym_strlcpy[] __asm__("strlcpy");
extern const char sym_strlen[] __asm__("strlen");
extern const char sym_strncasecmp[] __asm__("strncasecmp");
extern const char sym_strncmp[] __asm__("strncmp");
extern const char sym_strncpy[] __asm__("strncpy");
extern const char sym_strstr[] __asm__("strstr");
extern const char sym_strtod[] __asm__("strtod");
extern const char sym_strtol[] __asm__("strtol");
extern const char sym_strtoul[] __asm__("strtoul");
extern const char sym_tanf[] __asm__("tanf");

DynLibFunction dcr_imports[] = {
    {"__aeabi_atexit", (uintptr_t)sym_b___aeabi_atexit},
    {"__android_log_print", (uintptr_t)sym_b___android_log_print},
    {"__android_log_write", (uintptr_t)sym_b___android_log_write},
    {"__cxa_finalize", (uintptr_t)sym_b___cxa_finalize},
    {"__cxa_pure_virtual", (uintptr_t)sym_b___cxa_pure_virtual},
    {"__errno", (uintptr_t)sym___errno},
    {"__gnu_Unwind_Find_exidx", (uintptr_t)sym_b___gnu_Unwind_Find_exidx},
    {"__isfinitef", (uintptr_t)sym_b___isfinitef},
    {"__sF", (uintptr_t)sym_b___sF},
    {"__stack_chk_fail", (uintptr_t)sym_b___stack_chk_fail},
    {"__stack_chk_guard", (uintptr_t)sym_b___stack_chk_guard},
    {"_ctype_", (uintptr_t)sym_b__ctype_},
    {"_tolower_tab_", (uintptr_t)sym_b__tolower_tab_},
    {"_toupper_tab_", (uintptr_t)sym_b__toupper_tab_},
    {"abort", (uintptr_t)sym_b_abort},
    {"acosf", (uintptr_t)sym_acosf},
    {"asinf", (uintptr_t)sym_asinf},
    {"atan2f", (uintptr_t)sym_atan2f},
    {"atanf", (uintptr_t)sym_atanf},
    {"atoi", (uintptr_t)sym_atoi},
    {"bind", (uintptr_t)sym_b_bind},
    {"calloc", (uintptr_t)sym_calloc},
    {"clock_gettime", (uintptr_t)sym_b_clock_gettime},
    {"close", (uintptr_t)sym_b_close},
    {"cosf", (uintptr_t)sym_cosf},
    {"dlclose", (uintptr_t)sym_b_dlclose},
    {"dlerror", (uintptr_t)sym_b_dlerror},
    {"dlopen", (uintptr_t)sym_b_dlopen},
    {"dlsym", (uintptr_t)sym_b_dlsym},
    {"exit", (uintptr_t)sym_b_exit},
    {"exp", (uintptr_t)sym_exp},
    {"expf", (uintptr_t)sym_expf},
    {"fclose", (uintptr_t)sym_b_fclose},
    {"fcntl", (uintptr_t)sym_b_fcntl},
    {"fdopen", (uintptr_t)sym_b_fdopen},
    {"feof", (uintptr_t)sym_b_feof},
    {"fflush", (uintptr_t)sym_b_fflush},
    {"fgetc", (uintptr_t)sym_b_fgetc},
    {"fgets", (uintptr_t)sym_b_fgets},
    {"floor", (uintptr_t)sym_b_floor},
    {"floorf", (uintptr_t)sym_b_floorf},
    {"fmax", (uintptr_t)sym_fmax},
    {"fmodf", (uintptr_t)sym_fmodf},
    {"fopen", (uintptr_t)sym_b_fopen},
    {"fprintf", (uintptr_t)sym_b_fprintf},
    {"fputc", (uintptr_t)sym_b_fputc},
    {"fputs", (uintptr_t)sym_b_fputs},
    {"fread", (uintptr_t)sym_b_fread},
    {"free", (uintptr_t)sym_free},
    {"fseek", (uintptr_t)sym_b_fseek},
    {"ftell", (uintptr_t)sym_b_ftell},
    {"fwrite", (uintptr_t)sym_b_fwrite},
    {"getenv", (uintptr_t)sym_b_getenv},
    {"gettimeofday", (uintptr_t)sym_b_gettimeofday},
    {"log10f", (uintptr_t)sym_log10f},
    {"logf", (uintptr_t)sym_logf},
    {"lrand48", (uintptr_t)sym_lrand48},
    {"lseek", (uintptr_t)sym_b_lseek},
    {"malloc", (uintptr_t)sym_malloc},
    {"memchr", (uintptr_t)sym_memchr},
    {"memcmp", (uintptr_t)sym_memcmp},
    {"memcpy", (uintptr_t)sym_b_memcpy},
    {"memmove", (uintptr_t)sym_b_memmove},
    {"memset", (uintptr_t)sym_b_memset},
    {"nanosleep", (uintptr_t)sym_b_nanosleep},
    {"open", (uintptr_t)sym_b_open},
    {"pow", (uintptr_t)sym_pow},
    {"powf", (uintptr_t)sym_powf},
    {"printf", (uintptr_t)sym_b_printf},
    {"pthread_cond_broadcast", (uintptr_t)sym_b_pthread_cond_broadcast},
    {"pthread_cond_wait", (uintptr_t)sym_b_pthread_cond_wait},
    {"pthread_create", (uintptr_t)sym_b_pthread_create},
    {"pthread_getspecific", (uintptr_t)sym_b_pthread_getspecific},
    {"pthread_join", (uintptr_t)sym_b_pthread_join},
    {"pthread_key_create", (uintptr_t)sym_b_pthread_key_create},
    {"pthread_key_delete", (uintptr_t)sym_b_pthread_key_delete},
    {"pthread_mutex_destroy", (uintptr_t)sym_b_pthread_mutex_destroy},
    {"pthread_mutex_init", (uintptr_t)sym_b_pthread_mutex_init},
    {"pthread_mutex_lock", (uintptr_t)sym_b_pthread_mutex_lock},
    {"pthread_mutex_unlock", (uintptr_t)sym_b_pthread_mutex_unlock},
    {"pthread_mutexattr_destroy", (uintptr_t)sym_b_pthread_mutexattr_destroy},
    {"pthread_mutexattr_init", (uintptr_t)sym_b_pthread_mutexattr_init},
    {"pthread_mutexattr_settype", (uintptr_t)sym_b_pthread_mutexattr_settype},
    {"pthread_once", (uintptr_t)sym_b_pthread_once},
    {"pthread_self", (uintptr_t)sym_b_pthread_self},
    {"pthread_setschedparam", (uintptr_t)sym_b_pthread_setschedparam},
    {"pthread_setspecific", (uintptr_t)sym_b_pthread_setspecific},
    {"putchar", (uintptr_t)sym_b_putchar},
    {"puts", (uintptr_t)sym_b_puts},
    {"qsort", (uintptr_t)sym_qsort},
    {"raise", (uintptr_t)sym_b_raise},
    {"read", (uintptr_t)sym_b_read},
    {"realloc", (uintptr_t)sym_realloc},
    {"recvfrom", (uintptr_t)sym_b_recvfrom},
    {"remove", (uintptr_t)sym_b_remove},
    {"sched_get_priority_min", (uintptr_t)sym_b_sched_get_priority_min},
    {"sched_yield", (uintptr_t)sym_b_sched_yield},
    {"sendto", (uintptr_t)sym_b_sendto},
    {"setsockopt", (uintptr_t)sym_b_setsockopt},
    {"sinf", (uintptr_t)sym_sinf},
    {"snprintf", (uintptr_t)sym_b_snprintf},
    {"socket", (uintptr_t)sym_b_socket},
    {"sprintf", (uintptr_t)sym_b_sprintf},
    {"sqrtf", (uintptr_t)sym_b_sqrtf},
    {"srand48", (uintptr_t)sym_srand48},
    {"sscanf", (uintptr_t)sym_sscanf},
    {"strcasecmp", (uintptr_t)sym_strcasecmp},
    {"strcat", (uintptr_t)sym_strcat},
    {"strchr", (uintptr_t)sym_strchr},
    {"strcmp", (uintptr_t)sym_strcmp},
    {"strcpy", (uintptr_t)sym_strcpy},
    {"strdup", (uintptr_t)sym_strdup},
    {"strlcpy", (uintptr_t)sym_strlcpy},
    {"strlen", (uintptr_t)sym_strlen},
    {"strncasecmp", (uintptr_t)sym_strncasecmp},
    {"strncmp", (uintptr_t)sym_strncmp},
    {"strncpy", (uintptr_t)sym_strncpy},
    {"strstr", (uintptr_t)sym_strstr},
    {"strtod", (uintptr_t)sym_strtod},
    {"strtol", (uintptr_t)sym_strtol},
    {"strtoul", (uintptr_t)sym_strtoul},
    {"tanf", (uintptr_t)sym_tanf},
    {"usleep", (uintptr_t)sym_b_usleep},
    {"vprintf", (uintptr_t)sym_b_vprintf},
    {"vsnprintf", (uintptr_t)sym_b_vsnprintf},
    {"vsprintf", (uintptr_t)sym_b_vsprintf},
    {"", 0},
};

int dcr_imports_count = (int)(sizeof(dcr_imports) / sizeof(dcr_imports[0])) - 1;
