/* ssr_button_icons.h -- generated by tools/make_button_icons.py: where each
 * button is in resources/buttons/icons.png (one row, 96 pixels high). */
#define SSR_ICON_H 96
#define SSR_ICON_ROW_W 1382
#define SSR_ICON_COUNT 13
enum {
  SSR_ICON_A,
  SSR_ICON_B,
  SSR_ICON_X,
  SSR_ICON_Y,
  SSR_ICON_PLUS,
  SSR_ICON_MINUS,
  SSR_ICON_L,
  SSR_ICON_R,
  SSR_ICON_ZL,
  SSR_ICON_ZR,
  SSR_ICON_LSTICK,
  SSR_ICON_RSTICK,
  SSR_ICON_DPAD,
};
static const struct {
  int x, w;
} k_ssr_icons[SSR_ICON_COUNT] = {
    {0, 96}, /* A */
    {96, 96}, /* B */
    {192, 96}, /* X */
    {288, 96}, /* Y */
    {384, 96}, /* PLUS */
    {480, 96}, /* MINUS */
    {576, 120}, /* L */
    {696, 120}, /* R */
    {816, 139}, /* ZL */
    {955, 139}, /* ZR */
    {1094, 96}, /* LSTICK */
    {1190, 96}, /* RSTICK */
    {1286, 96}, /* DPAD */
};
